project:
  type: website

website:
  title: "A very tidy advent 2022"
  description: "25 days of tidyverse/r-lib functions, tips, and tricks."
  navbar:
    right:
      - icon: github
        href: https://github.com/tidyverse
        aria-label: Tidyverse GitHub page
format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: styles.css
    highlight-style: a11y-dark
    code-copy: true
    code-overflow: wrap

freeze: true
      

