project:
  type: website

website:
  title: "A very tidy advent 2022"
  site-url: https://mara.quarto.pub/tidy-advent-2022/
  description: "25 days of tidyverse and r-lib functions, tips, and tricks."
  navbar:
    right:
      - icon: rss-fill
        href: index.xml
        aria-label: RSS feed
      - icon: github
        href: https://github.com/batpigandme/2022-tidyverse-advent
        aria-label: GitHub repo with code for this page
  open-graph:
    locale: en_US
format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: styles.css
    highlight-style: a11y-dark
    code-copy: true
    code-overflow: wrap

execute: 
  freeze: auto
      

